# Executable names:
EXE = allocate
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = letter.o room.o allocator.o fileio.o main.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk
