# Executable names:
EXE = treefun
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = coloredout.o main.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk
